RISCV_ARCH := rv32imc
RISCV_ABI := ilp32
RISCV_MCMODEL := medlow


TARGET = temp


#CFLAGS += -DSIMULATION
#CFLAGS += -O2
#ASM_SRCS +=
#LDFLAGS +=
#INCLUDES += -I.

C_SRCS := \
	main.c \


COMMON_DIR = ..
TOOLCHAIN_DIR = ../../..
include ../common.mk
